title: mlserving
description: mlserving - Serving ML-Models Made Easy

remote_theme: rundocs/jekyll-rtd-theme

copyright:
  revision: true

edit: true
addons_branch: true

addons:
  - github
  - i18n
  - analytics

readme_index:
  with_frontmatter: true

exclude:
  - .gitignore
